=== arustleund/fighting-fantasy/src/main/resources/page.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.rustleund.com/fighting-fantasy/page" xmlns:tns="http://www.rustleund.com/fighting-fantasy/page" elementFormDefault="qualified">

	<element name="page" type="tns:page"></element>

	<complexType name="page">
		<sequence>
			<element name="pagenumber" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="pagetext" type="tns:pagetextContent" maxOccurs="1" minOccurs="1"></element>
			<element name="immediate" type="tns:commands" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="multicommand" type="tns:multicommand" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="battle" type="tns:battle" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="text" type="tns:text" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testluck" type="tns:testluck" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="keepminimum" type="tns:keepminimum" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="pagetextHtmlContent" mixed="true">
		<sequence>
			<any minOccurs="0" maxOccurs="unbounded" processContents="skip" />
		</sequence>
	</complexType>

	<complexType name="pagetextContent">
		<sequence>
			<element name="html" type="tns:pagetextHtmlContent" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>


	<complexType name="text">
		<sequence>
			<any minOccurs="0" maxOccurs="unbounded" processContents="skip" />
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>

	<complexType name="commands">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="adjustScale" type="tns:adjustScale" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="setFlag" type="tns:setFlag" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testFlag" type="tns:testFlag" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="displayText" type="tns:displayText" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="restoreScale" type="tns:restoreScale" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="addItem" type="tns:addItem" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testSkill" type="tns:testSkill" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testItem" type="tns:testItem" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="initPlayer" minOccurs="0" maxOccurs="unbounded">
				<complexType></complexType>
			</element>
			<element name="testStat" type="tns:testStat" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="link" type="tns:link" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testAnyFlag" type="tns:testAnyFlag" minOccurs="0" maxOccurs="unbounded"></element>
		</choice>
	</complexType>

	<complexType name="adjustScale">
		<attribute name="type" use="required" type="tns:scales"></attribute>
		<attribute name="amount" type="double" use="required"></attribute>
		<attribute name="promptOnFail" type="boolean" use="optional"></attribute>
		<attribute name="useAmountAsValue" type="boolean" use="optional"></attribute>
		<attribute name="useAmountAsPercent" type="boolean" use="optional"></attribute>
		<attribute name="round" use="optional">
			<simpleType>
				<restriction base="string">
					<enumeration value="up"></enumeration>
					<enumeration value="down"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="adjustInitialValue" type="boolean" use="optional"></attribute>
	</complexType>

	<simpleType name="scales">
		<restriction base="string">
			<enumeration value="time"></enumeration>
			<enumeration value="gold"></enumeration>
			<enumeration value="luck"></enumeration>
			<enumeration value="skill"></enumeration>
			<enumeration value="stamina"></enumeration>
			<enumeration value="provisions"></enumeration>
			<enumeration value="honor"></enumeration>
			<enumeration value="nemesis"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="setFlag">
		<annotation>
			<documentation>Sets a flag (true/false) for the entire game. Flags must be uniquely identified.</documentation>
		</annotation>
		<attribute name="id" type="int" use="required">
			<annotation>
				<documentation>The unique identifier of the flag to set.</documentation>
			</annotation>
		</attribute>
		<attribute name="value" type="boolean" use="optional"></attribute>
	</complexType>

	<complexType name="testFlag">
		<complexContent>
			<extension base="tns:testContent">
				<attribute name="id" type="int"></attribute>

			</extension>
		</complexContent>
	</complexType>

	<complexType name="testContent">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="successful" type="tns:commands" minOccurs="1" maxOccurs="1"></element>
			<element name="unsuccessful" type="tns:commands" minOccurs="1" maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="displayText">
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>

	<complexType name="battle">
		<sequence>
			<element name="enemies" type="tns:enemies" minOccurs="1" maxOccurs="1"></element>
			<element name="effects" type="tns:battleEffects" minOccurs="0" maxOccurs="1"></element>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
		<attribute name="fightEnemiesTogether" type="boolean" use="optional"></attribute>
		<attribute name="canFlee" type="boolean" use="optional"></attribute>
	</complexType>

	<complexType name="enemies">
		<sequence>
			<element name="enemy" type="tns:enemy" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="enemy">
		<attribute name="name" type="string" use="required">
			<annotation>
				<documentation>The name of the enemy.</documentation>
			</annotation>
		</attribute>
		<attribute name="skill" type="int" use="required">
			<annotation>
				<documentation>The enemy's skill level.</documentation>
			</annotation>
		</attribute>
		<attribute name="stamina" type="int" use="required">
			<annotation>
				<documentation>The enemy's stamina level.</documentation>
			</annotation>
		</attribute>
		<attribute name="poisonedWeapon" type="boolean" use="optional">
			<annotation>
				<documentation>true if the enemy has a poisoned weapon.</documentation>
			</annotation>
		</attribute>
	</complexType>

    <complexType name="battleEffects">
    	<sequence>
    		<element name="startBattle" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="startRound" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="playerFlee" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="playerHit" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="endRound" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="endBattle" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="restoreScale">
    	<attribute name="type" type="tns:scales" use="required"></attribute>
    </complexType>

    <complexType name="testluck">
    	<sequence>
    		<element name="successful" type="tns:testluckContent" minOccurs="1" maxOccurs="1"></element>
    		<element name="unsuccessful" type="tns:testluckContent" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="int" use="required"></attribute>
    </complexType>

    <complexType name="testluckContent">
    	<sequence>
    		<element name="p" type="tns:pagetextHtmlContent"></element>
    	</sequence>
    </complexType>

    <complexType name="multicommand">
    	<complexContent>
    		<extension base="tns:commands">
    			<attribute name="id" type="int" use="required"></attribute>

    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="addItem">
    	<attribute name="id" type="int" use="required"></attribute>
    	<attribute name="price" type="int" use="optional"></attribute>
    	<attribute name="quantity" type="int" use="optional"></attribute>
    	<attribute name="pageLimit" type="int" use="optional"></attribute>
    </complexType>

    <complexType name="testSkill">
    	<complexContent>
    		<extension base="tns:testContent">
    			<attribute name="diceRollAdjustment" type="int" use="optional"></attribute>

    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="keepminimum">
    	<attribute name="scale" type="tns:scales" use="required"></attribute>
    	<attribute name="value" type="int" use="required"></attribute>
    </complexType>

    <complexType name="testItem">
    	<complexContent>
    		<extension base="tns:testContent">
    			<attribute name="id" type="int" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="testStat">
    	<complexContent>
    		<extension base="tns:testContent">
    			<attribute name="stat" type="tns:scales" use="required"></attribute>
    			<attribute name="lessThan" type="int" use="optional"></attribute>
    			<attribute name="greaterThan" type="int" use="optional"></attribute>
    			<attribute name="atLeast" type="int" use="optional"></attribute>
    			<attribute name="atMost" type="int" use="optional"></attribute>
    			<attribute name="equal" type="int" use="optional"></attribute>
    			<attribute name="notEqual" type="int" use="optional"></attribute>
    			<attribute name="useInitialValue" type="boolean" use="optional"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="link">
    	<attribute name="page" type="string" use="required"></attribute>
    </complexType>

    <complexType name="testAnyFlag">
    	<complexContent>
    		<extension base="tns:testContent">
    			<attribute name="ids" type="string" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>
</schema>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/184.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagetext>
		<html>
			<p>
			You row all day and night and most of the next day, just hoping that your navigational instincts as to
			the direction of north are good. You must eat 2 meals during your journey, and by the time you reach
			Corpse Bay you are frozen, exhausted and feeling stiff all over. You desperately need rest and hot food!
			2 is added to your Time Track. Click <a href="http://link:304">here</a> to continue.
			</p>
		</html>
	</pagetext>
	<immediate>
		<adjustScale type="provisions" amount="-2" />
		<adjustScale type="time" amount="2" />
	</immediate>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/293.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagetext>
		<html>
			<p>
				'Who are you looking at?' you enquire as you sit down beside the robed man, staring deep into his eyes.
			</p>
		</html>
	</pagetext>
	<immediate>
		<testStat stat="nemesis" lessThan="4">
			<successful>
				<displayText id="0" />
			</successful>
			<unsuccessful>
				<displayText id="1" />
			</unsuccessful>
		</testStat>
	</immediate>
	<text id="0">
		<p>
			Your Nemesis score is 3 or below, click <a href="http://link:303">here</a>.
		</p>
	</text>
	<text id="1">
		<p>
			Your Nemesis score is 4 or higher, click <a href="http://link:357">here</a>.
		</p>
	</text>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/23.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagetext>
		<html>
			<p>
				Travelling along this broken trail is tricky. <a href="http://domulti:0"><i>Test your skill</i></a>.
			</p>
		</html>
	</pagetext>
	<immediate>
		<setFlag id="13" />
	</immediate>
	<multicommand id="0">
		<testSkill>
			<successful>
				<displayText id="0" />
				<displayText id="2" />
				<adjustScale type="time" amount="2" />
				<mustEatMeal amount="1" />
			</successful>
			<unsuccessful>
				<adjustScale type="stamina" amount="-2" />
				<displayText id="1" />
				<displayText id="2" />
				<adjustScale type="time" amount="2" />
				<mustEatMeal amount="1" />
			</unsuccessful>
		</testSkill>
	</multicommand>
	<text id="0">
		<p>
			You negotiate the trail safely.
		</p>
	</text>
	<text id="1">
		<p>
			You stumble several times on the treacherous, rocky ground and twist your ankle, losing 2 points from your
			Stamina.
		</p>
	</text>
	<text id="2">
		<p>
			2 is added to your Time Track, and you must now eat a meal. It is mid-afternoon when you see a large, winged creature in the sky,
			certainly no bird; your hope, that it may be a Dragon, is rewarded. But what a surprise you get &#8212; this is a green Dragon, normally
			a dweller in forests or jungles, not in the cold wastes of the northern lands! The beast lands close by and simply nods his massive
			head towards you. You clamber on to his back and hold on for dear life as he rises into the sky and flaps imperiously to a distant peak,
			where he lands and deposits you beside a huge cave mouth. Stepping off your enormous mount, you see that the tunnel opens into a vast
			crater in the mountain, probably half a kilometre wide. Within the crater, awaiting your descent down a seemingly endless set of 
			chiselled stone steps, is a circle of six huge adult Dragons &#8212; black, white, red, green, gold and silver. You are one of a mere 
			handful of people alive on Titan ever to have been invited to such a conclave! Click <a href="http://link:49">here</a> to continue.
		</p>
	</text>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/58.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagenumber>58</pagenumber>
	<pagetext>
		<html>
			<p>
				Searching the area around the mountain is time-consuming. 1 is added to your Time Track.
			</p>
		</html>
	</pagetext>
	<immediate>
		<adjustScale type="time" amount="1" />
		<testStat stat="nemesis" atLeast="5">
			<successful>
				<displayText id="0" />
			</successful>
			<unsuccessful>
				<displayText id="1" />
			</unsuccessful>
		</testStat>
	</immediate>
	<text id="0">
		<p>
			Your Nemesis score is 5 or higher, click <a href="http://link:137">here</a> to continue.
		</p>
	</text>
	<text id="1">
		<p>
			Your Nemesis score is less than 5, click <a href="http://link:169">here</a> to continue.
		</p>
	</text>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/35.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page https://github.com/arustleund/fighting-fantasy/raw/master/docs/page.xsd">
	<pagetext>
		<html>
			<p>
			The body is that of a dark-haired young man; he is blue with cold and is wearing a simple black robe
			with a knotted black cord tied round the waist. There is a distinctive tattoo on his left hand which
			shows a coiled black serpent with red glowing eyes. If you have an ice pick and wish to chip the body
			away from the ice, click <a href="http://domulti:0">here</a>. If you do not have an ice pick, or you 
			don't wish to do this, click <a href="http://link:112">here</a>.
			</p>
		</html>
	</pagetext>
	<immediate>
		<setFlag id="1" />
	</immediate>
	<multicommand id="0">
		<testItem id="10">
			<successful>
				<link page="328" />
			</successful>
			<unsuccessful />
		</testItem>
	</multicommand>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/30.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagetext>
		<html>
			<p>
			You open the door and admit the landlord of the tavern, together with two militiamen. You tell them
			the truth about what happened here, and they seem ready to believe you. 'Bad sorts, these,' says one
			of the militia as he turns over the body of one of the grey-robed men with his foot. 'We'll have to
			take you down to the jailhouse overnight, of course, but sleeping there is not so bad and frankly
			you may be safer.' Indeed, a night spent in jail means you are warm and well fed - and you even win
			3 Gold Pieces from your jailers, playing dice! Gain 1 Luck point. Click <a href="http://link:387">
			here</a> to continue.
			</p>
		</html>
	</pagetext>
	<immediate>
		<setFlag id="0" />
		<adjustScale type="gold" amount="3" />
		<adjustScale type="luck" amount="1" />
	</immediate>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/176.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagenumber>176</pagenumber>
	<pagetext>
		<html>
			<p>
			You have to carry the man for half a dozen kilometres before a trapper with a sled overtakes you. The
			burly trapper recognizes the victim and says he comes from the village of Sharndale, seven kilometres 
			further along. The two of you unload furs and goods from the sled, put the injured man on it, and you
			help by carrying the bulky furs along the road to Sharndale. You deliver the man to his family, who make
			him as comfortable as they can. The weather is closing in, with chill, sleeting rain drifting down from
			iron-grey clouds, and you'll not get to Rentarn before dark now. You are invited to stay with the family;
			they will give you some furs by way of thanks, as well as hot food and a comfortable bed for the night.
			2 is added to your Time Track and you gain 1 point of Honour. Click <a href="http://link:304">here</a>
			to continue.
			</p>
		</html>
	</pagetext>
	<immediate>
		<adjustScale type="time" amount="2" />
		<adjustScale type="honor" amount="1" />
		<addItem id="17" />
	</immediate>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/286.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page https://github.com/arustleund/fighting-fantasy/raw/master/docs/page.xsd">
	<pagetext>
		<html>
			<p>
			The sign of the Rudderless Galley swings, creaking, to and fro in the north wind. Approaching the
			dockside tavern past the alleys and byways, you thought you saw a grey-robed man duck into the
			shadows just before you reached the tavern door, or was it just a trick of the light? You push
			past the seamen and merchants inside the tavern, walk across the sawdust floor to the stairway and 
			climb as far as the landing. You make your way to the third door along, as instructed, and take the
			silver key from your pocket. <a href="http://domulti:0"><i>Test your Skill</i></a>.
			</p>
		</html>
	</pagetext>
	<multicommand id="0">
		<testSkill>
			<successful>
				<link page="261" />
			</successful>
			<unsuccessful>
				<link page="314" />
			</unsuccessful>
		</testSkill>
	</multicommand>
</page>
