=== arustleund/fighting-fantasy/src/main/resources/page.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.rustleund.com/fighting-fantasy/page" xmlns:tns="http://www.rustleund.com/fighting-fantasy/page" elementFormDefault="qualified">

	<element name="page" type="tns:page"></element>

	<complexType name="page">
		<sequence>
			<element name="pagenumber" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="pagetext" type="tns:pagetextContent" maxOccurs="1" minOccurs="1"></element>
			<element name="immediate" type="tns:commands" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="multicommand" type="tns:multicommand" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="battle" type="tns:battle" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="text" type="tns:text" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testluck" type="tns:testluck" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="keepminimum" type="tns:keepminimum" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="pagetextHtmlContent" mixed="true">
		<sequence>
			<any minOccurs="0" maxOccurs="unbounded" processContents="skip" />
		</sequence>
	</complexType>

	<complexType name="pagetextContent">
		<sequence>
			<element name="html" type="tns:pagetextHtmlContent" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>


	<complexType name="text">
		<sequence>
			<any minOccurs="0" maxOccurs="unbounded" processContents="skip" />
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>

	<complexType name="commands">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="adjustScale" type="tns:adjustScale" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="setFlag" type="tns:setFlag" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testFlag" type="tns:testFlag" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="displayText" type="tns:displayText" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="restoreScale" type="tns:restoreScale" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="addItem" type="tns:addItem" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testSkill" type="tns:testSkill" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testItem" type="tns:testItem" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="initPlayer" minOccurs="0" maxOccurs="unbounded">
				<complexType></complexType>
			</element>
			<element name="testStat" type="tns:testStat" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="link" type="tns:link" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="testAnyFlag" type="tns:testAnyFlag" minOccurs="0" maxOccurs="unbounded"></element>
		</choice>
	</complexType>

	<complexType name="adjustScale">
		<attribute name="type" use="required" type="tns:scales"></attribute>
		<attribute name="amount" type="double" use="required"></attribute>
		<attribute name="promptOnFail" type="boolean" use="optional"></attribute>
		<attribute name="useAmountAsValue" type="boolean" use="optional"></attribute>
		<attribute name="useAmountAsPercent" type="boolean" use="optional"></attribute>
		<attribute name="round" use="optional">
			<simpleType>
				<restriction base="string">
					<enumeration value="up"></enumeration>
					<enumeration value="down"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="adjustInitialValue" type="boolean" use="optional"></attribute>
	</complexType>

	<simpleType name="scales">
		<restriction base="string">
			<enumeration value="time"></enumeration>
			<enumeration value="gold"></enumeration>
			<enumeration value="luck"></enumeration>
			<enumeration value="skill"></enumeration>
			<enumeration value="stamina"></enumeration>
			<enumeration value="provisions"></enumeration>
			<enumeration value="honor"></enumeration>
			<enumeration value="nemesis"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="setFlag">
		<annotation>
			<documentation>Sets a flag (true/false) for the entire game. Flags must be uniquely identified.</documentation>
		</annotation>
		<attribute name="id" type="int" use="required">
			<annotation>
				<documentation>The unique identifier of the flag to set.</documentation>
			</annotation>
		</attribute>
		<attribute name="value" type="boolean" use="optional"></attribute>
	</complexType>

	<complexType name="testFlag">
		<complexContent>
			<extension base="tns:testContent">
				<attribute name="id" type="int"></attribute>

			</extension>
		</complexContent>
	</complexType>

	<complexType name="testContent">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="successful" type="tns:commands" minOccurs="1" maxOccurs="1"></element>
			<element name="unsuccessful" type="tns:commands" minOccurs="1" maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="displayText">
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>

	<complexType name="battle">
		<sequence>
			<element name="enemies" type="tns:enemies" minOccurs="1" maxOccurs="1"></element>
			<element name="effects" type="tns:battleEffects" minOccurs="0" maxOccurs="1"></element>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
		<attribute name="fightEnemiesTogether" type="boolean" use="optional"></attribute>
		<attribute name="canFlee" type="boolean" use="optional"></attribute>
	</complexType>

	<complexType name="enemies">
		<sequence>
			<element name="enemy" type="tns:enemy" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="enemy">
		<attribute name="name" type="string" use="required">
			<annotation>
				<documentation>The name of the enemy.</documentation>
			</annotation>
		</attribute>
		<attribute name="skill" type="int" use="required">
			<annotation>
				<documentation>The enemy's skill level.</documentation>
			</annotation>
		</attribute>
		<attribute name="stamina" type="int" use="required">
			<annotation>
				<documentation>The enemy's stamina level.</documentation>
			</annotation>
		</attribute>
		<attribute name="poisonedWeapon" type="boolean" use="optional">
			<annotation>
				<documentation>true if the enemy has a poisoned weapon.</documentation>
			</annotation>
		</attribute>
	</complexType>

    <complexType name="battleEffects">
    	<sequence>
    		<element name="startBattle" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="startRound" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="playerFlee" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="playerHit" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="endRound" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    		<element name="endBattle" type="tns:commands" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="restoreScale">
    	<attribute name="type" type="tns:scales" use="required"></attribute>
    </complexType>

    <complexType name="testluck">
    	<sequence>
    		<element name="successful" type="tns:testluckContent" minOccurs="1" maxOccurs="1"></element>
    		<element name="unsuccessful" type="tns:testluckContent" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="int" use="required"></attribute>
    </complexType>

    <complexType name="testluckContent">
    	<sequence>
    		<element name="p" type="tns:pagetextHtmlContent"></element>
    	</sequence>
    </complexType>

    <complexType name="multicommand">
    	<complexContent>
    		<extension base="tns:commands">
    			<attribute name="id" type="int" use="required"></attribute>

    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="addItem">
    	<attribute name="id" type="int" use="required"></attribute>
    	<attribute name="price" type="int" use="optional"></attribute>
    	<attribute name="quantity" type="int" use="optional"></attribute>
    	<attribute name="pageLimit" type="int" use="optional"></attribute>
    </complexType>

    <complexType name="testSkill">
    	<complexContent>
    		<extension base="tns:testContent">
    			<attribute name="diceRollAdjustment" type="int" use="optional"></attribute>

    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="keepminimum">
    	<attribute name="scale" type="tns:scales" use="required"></attribute>
    	<attribute name="value" type="int" use="required"></attribute>
    </complexType>

    <complexType name="testItem">
    	<complexContent>
    		<extension base="tns:testContent">
    			<attribute name="id" type="int" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="testStat">
    	<complexContent>
    		<extension base="tns:testContent">
    			<attribute name="stat" type="tns:scales" use="required"></attribute>
    			<attribute name="lessThan" type="int" use="optional"></attribute>
    			<attribute name="greaterThan" type="int" use="optional"></attribute>
    			<attribute name="atLeast" type="int" use="optional"></attribute>
    			<attribute name="atMost" type="int" use="optional"></attribute>
    			<attribute name="equal" type="int" use="optional"></attribute>
    			<attribute name="notEqual" type="int" use="optional"></attribute>
    			<attribute name="useInitialValue" type="boolean" use="optional"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="link">
    	<attribute name="page" type="string" use="required"></attribute>
    </complexType>

    <complexType name="testAnyFlag">
    	<complexContent>
    		<extension base="tns:testContent">
    			<attribute name="ids" type="string" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>
</schema>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/109.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagetext>
		<html>
		</html>
	</pagetext>
	<immediate>
		<testFlag id="3">
			<successful>
				<displayText id="0" />
			</successful>
			<unsuccessful>
				<displayText id="1" />
			</unsuccessful>
		</testFlag>
	</immediate>
	<multicommand id="0">
		<testSkill diceRollAdjustment="2">
			<successful>
				<displayText id="2" />
				<setFlag id="5" />
			</successful>
			<unsuccessful>
				<displayText id="3" />
			</unsuccessful>
		</testSkill>
	</multicommand>
	<text id="0">
		<p>
			<a href="http://domulti:0"><i>Test your Skill</i></a> (adding 2).
		</p>
	</text>
	<text id="1">
		<p>
			You easily escape, click <a href="http://link:387">here</a>.
		</p>
	</text>
	<text id="2">
		<p>
			You evade them and jump down into the back streets, where you evade their pursuit.
			But now you're going to be hunted by the militia, which will make your quest
			very difficult in the future. Click <a href="http://link:387">here</a> to continue.
		</p>
	</text>
	<text id="3">
		<p>
			You are caught by the guards. Click <a href="http://link:143">here</a> to continue.
		</p>
	</text>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/143.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page https://github.com/arustleund/fighting-fantasy/raw/master/docs/page.xsd">
	<pagetext>
		<html>
			<p>
				The militia are very suspicious indeed, although they clearly know the grey-robed 
				men to be evil people. They cart you off to jail and keep you there for
				some time.
			</p>
		</html>
	</pagetext>
	<immediate>
		<setFlag id="0" />
		<testFlag id="4">
			<successful>
				<displayText id="0" />
				<adjustScale type="time" amount="10" />
			</successful>
			<unsuccessful>
				<displayText id="1" />
				<adjustScale type="time" amount="4" />
			</unsuccessful>
		</testFlag>
	</immediate>
	<text id="0">
		<p>
			Because you tried to escape through the window of the tavern room,
			they hold you for five days (add 10 to your Time Track).
			Then they turf you out.
			Click <a href="http://link:387">here</a> to continue.
		</p>
	</text>
	<text id="1">
		<p>
			Because you didn't try to escape through the window of the tavern room,
			they hold you for two days (add 4 to your Time Track).
			Then they turf you out.
			Click <a href="http://link:387">here</a> to continue.
		</p>
	</text>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/171.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagetext>
		<html>
			
		</html>
	</pagetext>
	<immediate>
		<testStat stat="stamina" atLeast="20">
			<successful>
				<displayText id="0" />
			</successful>
			<unsuccessful>
				<displayText id="1" />
			</unsuccessful>
		</testStat>
	</immediate>
	<multicommand id="0">
		<adjustScale type="gold" amount="-4" promptOnFail="true" />
		<setFlag id="2" />
		<link page="122" />
	</multicommand>
	<multicommand id="1">
		<adjustScale type="gold" amount="-10" promptOnFail="true" />
		<link page="122" />
	</multicommand>
	<text id="0">
		<p>
			You have a Stamina of 20 or more, the first mate looks you over and decides you're a strong
			fellow, so you can get passage for a mere 4 Gold Pieces, if you're prepared to work aboard ship,
			slaving at rope-tarring and deck-scrubbing. You'll get a bunk to sleep in, but you'll have to 
			provide your own food! If you want to <a href="http://domulti:0">accept this offer</a> and can pay, 
			the number of meals which you are told to consume during the journey aboard ship will be doubled.
			Otherwise you must <a href="http://link:212">travel by land</a>.
		</p>
	</text>
	<text id="1">
		<p>
			Your Stamina is below 20, so you have to <a href="http://domulti:1">play the full fare of 10 Gold
			Pieces</a>; otherwise you must <a href="http://link:212">travel by land</a>.
		</p>
	</text>
</page>

=== arustleund/fighting-fantasy/src/main/resources/nightdragon/pages/intro.xml
<page
	xmlns="http://www.rustleund.com/fighting-fantasy/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rustleund.com/fighting-fantasy/page ../../page.xsd">
	<pagetext>
		<html>
			<p>
				'Beware Blacksand!' The words still ring in your ears. This is a city ruled by evil, full of thugs and rogues. Every new morning
				brings a slumped body in a back alley, its throat cut from ear to ear. Port Blacksand isn't a place anyone wants to stay in for
				long.
			</p>
			<p>
				You're here because a man you trusted whispered that a great challenge might be found here for you. You live for adventure and
				great deeds, and your friend's expression told you that this was no trivial summons. Setting aside your dislike of Blacksand,
				you found yourself sitting in the Hemlock tavern in Clog Street until late into the night, waiting for a messenger who seemed
				never to come. It was long after the witching hour, with the tavern about to close for the night, when you were finally shown down
				to the cellars where a mysterious robed guest was waiting. You drew your sword when you found that a Dark Elf awaited you, but the
				weary way he held up his hand and mumbled that he was not here to harm you made you draw back.
			</p>
			<p>
				Now you listen to his strange tale. He speaks as if he does not have much time left to him to deliver it. 'I have come from the far
				north, from the Dragon Reaches. A great and terrible enemy is growing even more powerful there, and he will come to threaten all 
				Allansia if he is not overcome. My people have tried, but we are few in number and we could not even defeat the Stalkers protecting
				the monster. The sands of time run low. Only a great hero could hope to overcome the Night Dragon. It is an ancient being, more
				powerful than the Old Ones. The Dragons themselves have said to me that even a mortal Dragon could not hope to scratch a single
				scale on the Ancient's hide.'
			</p>
			<p>
				An Ancient Dragon! Even a mortal Dragon is a terrifying enemy. How can you possibly hope to overcome one far more powerful than its
				mortal kin? A human would be destroyed with a single flick of such a monster's claws.
			</p>
			<p>
				The Dark Elf sees your thoughts reflected in your eyes. 'There would be no hope at all, were it not for buried magic which the 
				Dragons know of. They say it could make a warrior powerful far beyond mortal limits, if the right person came to take the sword,
				shield and armour of heroes of legend and face the Night Dragon. I sought for such a warrior for a long time; yours was the name
				I heard mentioned over and over again.'
			</p>
			<p>
				You are disbelieving, astonished by what the Dark Elf says. Suddenly he coughs violently and you see blood staining the
				handkerchief he holds over his mouth.
			</p>
			<p>
				When he can speak again, there is a terrible urgency in his voice. 'Listen, human. Dragons themselves have told me that when the
				creature awakens, his shadow will lengthen over all the land and his dreams of carnage and slaughter will be a reality. They told me
				that the Night Dragon was within Death's army in the war of gods, before time came to Titan and brought the mortal race with it.
				Can you imagine how powerful this horror is becoming as it awakens? Never mind your arch-mages, necromancers, petty tyrants and
				despots. If the Night Dragon reawakens, they will be scattered like dust in the wind. As will you and I. There are signs already
				of his stirring from Dreamtime; his Stalkers have begun to roam the northern mountains &#8212; marauding reptile nightmares that they
				are. Fortunately they are still few, and not yet as strong as they will become else I would not be here.'
			</p>
			<p>
				You notice the heavy scars on the Dark Elf's arm as he gestures to emphasize the point, and your initial suspicion of him begins
				to evaporate. He continues beseeching your help.
			</p>
			<p>
				'The Dragons say that they are bound by their own oath to Kilanirax, their god and creator. This oath forbids any mortal Dragon to 
				offer force to an Ancient One, should one so much as lift a claw against an Ancient, it would be struck down at once by a deadly
				curse. Thus they are forced to seek help from others. They are surely not indulging in lies or deceit; in the Conclave, I saw a
				Dragon of each type &#8212; Gold, Silver, White, Black, Green, Red. Only extraordinary circumstances could bring together a full
				Conclave; the Dragons of Law and Chaos have no love for each other. For them to meet means that a terrible danger must be at hand,
				as they say. All I ask is that you travel to meet the Conclave of Dragons and hear what they have to say.'
			</p>
			<p>
				'Go north to the port of Rentarn, and there take a room at the Rudderless Galley tavern. Here &#8212; take this silver key and use
				it to admit yourself to the room there which has been readied for you. A messenger will meet you in the tavern and he will tell you
				how to find the Dragon Conclave. Look, I even give you the ten Gold Pieces you will need to pay for the sea voyage there.' For a
				moment, the Dark Elf almost grins, albeit painfully. 'Although you could save some gold by taking the coast road, of course.
				<i>Please</i>. I only ask you to travel and listen.'
			</p>
			<p>
				How can you refuse? You take the silver key and the 10 Gold Pieces.
			</p>
			<p>
				The Dark Elf gets up and makes to leave, first telling you that you can sleep in this safe tavern tonight. He looks back at you
				with eyes dulled by pain, and his hands have a fine tremor you didn't see before. 'I do not want my people to die, any more than
				you wish all the humans in this land to be slaughtered. If it has cost me my own life to find you, my people will remember me.'
				He turns on his heel, coughing horribly, and limps out of the cellar.
			</p>
			<p>
				You do not have pleasant dreams this night ...
			</p>
			<p>
				Click <a href="http://link:1">here</a> to continue.
			</p>
		</html>
	</pagetext>
	<immediate>
		<adjustScale type="gold" amount="10" />
		<addItem id="4" />
	</immediate>
</page>
